package com.sonymobile.generalobjectdetector;

/**
 * This enum is generated by label_code_generator.py.
 */
public enum GeneralObjectLabel {
    NONE_OF_THE_ABOVE(0, "background"),
    PERSON(1, "person"),
    ERS_7(2, "aibo"),
    ERS_110(2, "aibo"),
    ERS_210(2, "aibo"),
    ERS_220(2, "aibo"),
    ERS_31L(2, "aibo"),
    LATTE(2, "aibo"),
    MACARON(2, "aibo"),
    PINKBALL(3, "pinkball"),
    PINKBONE(4, "aibone"),
    CAT(5, "cat"),
    CHAIR(6, "chair"),
    DOG(7, "dog"),
    SOFA(8, "sofa"),
    TVMONITOR(9, "tvmonitor"),
    FACE(10, "face"),
    TORSO(11, "torso"),
    PINKCHARGER(12, "charger"),
    AIBO(2, "aibo");

    GeneralObjectLabel(int number, String name) {
        this.number = number;
        this.name = name;
    }

    public final int number;

    public final String name;
}
